### PR TITLE
resolver metadb with own darkmetadb

### PR DESCRIPTION
**Pull request by Sadrak**
To use an own darkmetadb everything was programmed, simple one line was missing to use this feature.

### CODE REVIEW

**Comment by skaji** [comment]
Does https://github.com/skaji/cpm/commit/01416c3723a04ac195936fb07d9cd67f711fa0e8 work for you?

**Comment by Sadrak** [comment]
works as expected.

But i dislike the argument swap between @arg == 1 and @arg == 2. $arg[0] should always the mirror and $arg[1] the darkmetadb. Perhaps this was only a typo?

**Comment by skaji** [comment]
This is more consistent with how to parse args in resolver 02package.

**Comment by Sadrak** [comment]
I did not know that 02package has also a second argument. This looks like an undocumented feature. And from the code i guess the first argument stay the mirror(+path) and the second works as a title or something similar.

Back to metadb: perhaps `normalize_mirror` is also a good option for `$uri`

**Comment by skaji** [comment]
@Sadrak thanks.
At last, can you please revert changes in cpm and lib/App/cpm.pm?
They will be updated in release steps.

Then I will merge this PR.

**Comment by Sadrak** [comment]
I have a strange error:

```
cpm install --global --no-show-progress --show-build-log-on-failure \
             --resolver 02packages,https://darkpan/ \
             --resolver metadb,https://darkmetadb/,https://darkpan/ \
             --resolver 02packages \
             --resolver metadb
```

our darkpan and darkmetadb only contains our modules. But with this arguments i get the following error:

2019-11-07T17:05:45,17,Dist::Zilla| Resolved Dist::Zilla (0) -> https://darkmetadb/authors/id/R/RJ/RJBS/Dist-Zilla-6.012.tar.gz from MetaDB
2019-11-07T17:05:46,18,Dist-Zilla-6.012| -> OK
2019-11-07T17:05:46,18,Dist-Zilla-6.012| Unpacking Dist-Zilla-6.012.tar.gz
2019-11-07T17:05:46,18,Dist-Zilla-6.012| 
2019-11-07T17:05:46,18,Dist-Zilla-6.012| gzip: stdin: not in gzip format
2019-11-07T17:05:46,18,Dist-Zilla-6.012| /bin/tar: Child returned status 1
2019-11-07T17:05:46,18,Dist-Zilla-6.012| /bin/tar: Error is not recoverable: exiting now
2019-11-07T17:05:46,18,Dist-Zilla-6.012| Failed to fetch/configure distribution

Swapping the ordering (first generic, second dark) resolv this problem, but i don't understand the problem.

**Comment by skaji** [comment]
Released https://metacpan.org/release/SKAJI/App-cpm-0.989

I tweaked two things:

* Because normalize_mirror() is literally for mirrors, do not call it on metadb uri. https://github.com/skaji/cpm/commit/267dd6e9a3a8fe4202fe536a8503445414a6ec0b
* I don't think we need `--resolver 02package` in custom metadb example. https://github.com/skaji/cpm/commit/7342150d327981317d7f8a5e30351d5d329fd648

**Comment by Sadrak** [comment]
ok, i would prefer to rename `normalize_mirror()` to `normalize_uri()` and use is again for $uri. The problem is the added trailing / for mirror-uris but not for the metadb-uris. That is confusing (and not expectable).

Or keep `normalize_mirror()` as a plain wrapper for a new `normalize_uri()` and call the corresponding sub. 

Also the pod-hint is now incorrect, because it will directly concat the path and you will get https://example.com/darkmetadbhistory/common::sense

**Comment by Sadrak** [comment]
Sorry to bother you, but the pod is still broken & not intuitive. Currently the metadb url need a / at the end while the mirror url is allowed a / optional at the end (and add a / if not provided).

**Comment by skaji** [comment]
Both work.
```
❯ cpm install -r metadb,https://cpanmetadb.plackperl.org/v1.0,https://www.cpan.org App::FatPacker
❯ cpm install -r metadb,https://cpanmetadb.plackperl.org/v1.0/,https://www.cpan.org App::FatPacker
```

**Comment by Sadrak** [comment]
OK, now I found out why this works (in MetaDB.pm):

```perl
    s{/*$}{/} for $uri, $mirror;
```

Have a nice day and thanks for accepting my MR.

**Pull request merged**
