### PR TITLE
Fix win32 issues

### PR DESCRIPTION
**Pull request by charsbar**
With these changes, all the xt tests pass for me, under Win7+strawberry 5.22.3 as of this writing.

### CODE REVIEW

**Comment by zmughal** [comment]
This should also close <https://github.com/skaji/cpm/issues/77>.

**Comment by skaji** [comment]
I'm preparing a development environment in Windows10...
Please wait a moment.

**Comment by skaji** [comment]
I also confirmed that the tests passed on Win10 + Strawberry 5.24.

**Comment by skaji** [comment]
@charsbar Thanks! This is a big step, I think. I merge this PR.

P.S. To improve Win32 support, we should do:

* Use build.log.$(time) and copy it to build.log at last (like cpanminus)
* Use https://github.com/skaji/Command-Runner to execute external commands
* Add 'use IO::File' to App::cpm::Logger::File
* Take care of absence of environment variable HOME ( #97 )
* Disable colorizing logs
* Take care of absence of gzip command (xt/21_resolver_option.t (CPAN::Mirror::Tiny) uses gzip command)

**Comment by charsbar** [comment]
> Add 'use IO::File' to App::cpm::Logger::File
Currently it's loaded at "new". Do you mean it should be used everywhere?

> Take care of absence of environment variable HOME ( #97 )
#100 

> Disable colorizing logs
#101 

> Take care of absence of gzip command (xt/21_resolver_option.t (CPAN::Mirror::Tiny) uses gzip command)
Isn't it already addressed in CPAN::Mirror::Tiny (by falling down to Archive::Tar)?

**Comment by skaji** [comment]
>> Add 'use IO::File' to App::cpm::Logger::File

> Currently it's loaded at "new". Do you mean it should be used everywhere?

>> Take care of absence of gzip command (xt/21_resolver_option.t (CPAN::Mirror::Tiny) uses gzip command)

> Isn't it already addressed in CPAN::Mirror::Tiny (by falling down to Archive::Tar)?

Oops, I missed those!

**Comment by skaji** [comment]
I created an issue against menlo https://github.com/miyagawa/cpanminus/issues/545

**Pull request merged**
