### PR TITLE
Add resolver: script

### PR DESCRIPTION
**Pull request by perlancar**
Implements #43.

### CODE REVIEW

**Comment by perlancar** [comment]
Example usage:

This will use MetaCPAN resolver because the Script resolver will decline (return undef) because package contains /::/:

    % cpm install -vg -r script -r MetaCPAN App::CSVUtils

This will be resolved by the Script resolver:

    % cpm install -vg -r script -r MetaCPAN csv-add-field

**Comment by skaji** [comment]
I'm not very familiar with elasticsearch, but we might search script name againt MetaCPAN.
eg: https://gist.github.com/skaji/9dddfd3e5c81f278d12c28656ba3e46b

**Comment by skaji** [comment]
`s{http://api.metacpan.org/v0}{https://fastapi.metacpan.org/v1}` does not work though :/

**Comment by perlancar** [comment]
That's nice. I think we still need to require the "path" to be one of these:

    bin/$name
    script/$name
    scripts/$name

Because otherwise shared files or examples are also included, e.g.

    share/examples/example1.pl
    examples/example1.pl

https://gist.github.com/perlancar/56169c041c48fc0ad80a958f745eb5e5

**Comment by skaji** [comment]
Closing for now.

**Pull request closed without merging**
