### PR TITLE
Added missing prereq as reported by CPANTS.

### PR DESCRIPTION
**Pull request by manwar**
Hi @skaji 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by skaji** [comment]
It is a part of Menlo-Legacy distribution. I don't think we should require it explicitly.

**Comment by manwar** [comment]
Point taken completely.
However it doesn't harm to explicitly mention it as relying on other distribution prereq may break in future, imho.

**Comment by skaji** [comment]
> relying on other distribution prereq may break in future

It is true.
However cpm **deeply** depends on Menlo,
so if Menlo is reorganized, cpm should follow that carefully anyway.

**Comment by skaji** [comment]
@manwar Thanks for the PR.
However I close this because of the above reason.

**Pull request closed without merging**
